language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t rymunin/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true rymunin/docker-react npm run test
    
