language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t rymunin/docker -f Dockerfile.dev . 

script:
    - docker run -e CI=true rymunin/docker npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-624750282849"
    bucket_path: "docker"

    on:
        branch: master

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
